Preserve scroll upon inserting new fragment
Juicy/imported-template pull request #62
Opened 2019-03-25 19:17 UTC by alshakero

Turns out this is the root of the scroll tricks not working in Palindrom. Prepending DOM elements scrolls to top by default see https://stackoverflow.com/questions/5688362/how-to-prevent-scrolling-on-prepend.

Fixes point 4 of https://github.com/Palindrom/Palindrom/issues/216

2019-03-27 10:29 UTC, warpech commented
I am not sure I understand why is this needed. 

I tried to reproduce the problem on a smaller scale and it doesn't seem like `insertBefore` induces any scrolling: https://jsfiddle.net/5afoyvs6/. Can you please edit the Fiddle to demonstrate the problem that this is fixing?

Ideally, I would like to see an explanation for this behavior from the DOM spec and a test for it that is failing without this fix.

2019-03-27 10:29 UTC, warpech requested changes
I am not sure I understand why is this needed.

I tried to reproduce the problem on a smaller scale and it doesn't seem like insertBefore induces any scrolling: https://jsfiddle.net/5afoyvs6/. Can you please edit the Fiddle to demonstrate the problem that this is fixing?

Ideally, I would like to see an explanation for this behavior from the DOM spec and a test for it that is failing without this fix.

2019-03-28 13:48 UTC, alshakero commented
Now it's reproduced in the fiddle https://jsfiddle.net/4uysz39v/

2019-03-28 14:06 UTC, alshakero commented
I think it would make more sense to give this to @tomalec. I think it would take him much less time.

2019-03-28 14:52 UTC, warpech commented
I changed the fiddle to have some console logs: https://jsfiddle.net/oxswf3nz/

I expect `scroll position 2` to be the same as `scroll position 3` and it works like that. Can you explain what the problem is, because I still don't see it?

![image](https://user-images.githubusercontent.com/566463/55167455-4dcdd480-5171-11e9-8c19-33c8c6537924.png)

2019-03-28 15:53 UTC, alshakero commented
I feel that the fiddle will be a waste of time. Can you put a breaking point on [this line](https://github.com/Juicy/imported-template/blob/master/imported-template.html#L100) of `imported-template` and try to reproduce the scroll bug using [these steps](https://github.com/Palindrom/Palindrom/pull/228#pullrequestreview-216036651) please? 

You'll see that the scroll will jump immediately after you click Play to overcome the breakpoint.

2019-04-01 15:38 UTC, tomalec commented
Could you make a test case for it i this repo? I'm still not sure whether it's purely `imported-template` issue. Not for example an issue with the way we use `dom-bind`.

2019-04-19 15:09 UTC, tomalec commented
Seems to be an issue of `dom-bind`. If the partial view contains only static HTML, the scroll position is preserved even without this change.

2019-04-22 22:52 UTC, warpech commented
I am not surprised. We are removing DOM nodes before appending the new DOM nodes, so what else could be expected? 

I did some micro investigation:

Whenever the user is navigating to a page that replaces a rendered partial, [this line in starcounter-include](https://github.com/Starcounter/starcounter-include/blob/554abe5d313c22411dbc1f08f04c079d5b11bc74/starcounter-include.html#L233), causes [this line in juicy-html](https://github.com/Juicy/juicy-html/blob/fbdf12cf3ce63684b82cac9dd690e5e9885e581c/juicy-html.html#L139) to remove the `dom-bind`, which upon disconnection performs [removes all rendered DOM children](https://github.com/Polymer/polymer/blob/b8f3b79c725749a360650a5e487759053f5f8329/lib/elements/dom-bind.js#L87).

I think we are back to square one. It is obvious to me that replacing a DOM subtree with another subtree will force scroll to top of the replaced element. The question is, where do we put the logic to restore the scroll position. I think it should be in `starcounter-include`, because that's where the Starcounter partial logic meets the DOM binding logic.

2019-04-23 11:40 UTC, tomalec commented
I think in ideal world, dom-bind. Should have an attribute to preserve-scroll, but given it's deprecated, I agree sc-include is a fair compromise. But given the asynchronous cascade of nested partials.

In my investigatio, I checked imported template switching views which was also removing and appending nodes, but the position was preserved.


I'm fine with merging this as a quick fix for urgent problem (if any)
But for sure we should add at least one test (even post-mergem), and revisitthe problem when desiging "flattened blended pages" and "Palindrom's template instantiation".

2019-11-04 11:03 UTC, alshakero commented
Closed as outdated.

2019-11-04 11:04 UTC, closed without merging